// Auto-generated file - DO NOT EDIT MANUALLY
// This file is automatically generated by scripts/generate-music-list.js
// Run 'npm run generate-music' to regenerate this file

export const musicFiles: string[] = [
  "/music/La leçon particulière.mp3",
  "/music/die with smile.mp3"
];

// Export for easy access
export default musicFiles;
